# docker-compose.yml

version: '3.3'

services:
  app:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 
    volumes:
      - .:/app
    ports:
      - 8008:8000
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  